### ISSUE TITLE
Looking For C# developer and Front End Developer(s)

### ISSUE THREAD

**Issue by dynamoRando** [fix-the-internet/spring-mvp-lab#29]
Hey all -

For Mozilla's Sprint "Fix The Internet" project I am debating on rebooting my previous code base here -

https://github.com/dynamoRando/FrostDB

And starting over again from scratch; as my code has gotten pretty messy. I'm not a C# developer by nature; I've just been teaching myself along the way with my code base.

The goal is a concept I called "cooperative databases" where the idea is that users should be able to own their own data, and agree to participate in a database system to allow the application author (and database author) access to that data in a defined contract agreement.

The idea that I had I wrote about in a paper here -

https://github.com/dynamoRando/CooperativeDatabaseSystems

And a lot of those ideas I decided to obsolete in favor of an MVP. That said; I'm still having trouble getting my code to work.

The goal of this project is incredibly similar to the efforts of the SOLID project (https://solid.mit.edu/) but I wanted to try and make it easy for developers to ensure users owned their own data without having to learn about LINKED DATA and a new language.

The goals was to build a database system that was SQL-like; but would store user's data in their own "data store" and in the primary database it would contain references to that data whenever an app made requests.

From an application developer's experience, I wanted to minimize what "new" things an application developer would need to learn. Since I'm familiar with SQL, I was thinking just extended a few new SQL keywords to make it work; and perhaps having the author of a database also author a "data contract" for users of the database to define what would be stored, and where, and who had access rights to it.

I think I should have explored trying to engineer a NoSQL like solution rather than trying to make a SQL like database. 

I have no software engineering experience, so things like b-trees and TCP/IP code that I "wrote" on my own are just examples that I've copied from the internet.

If you're interested, please feel free to reply or find me on the slack channel.

**Comment by MirageOwl** [comment]
I have taken a look at your paper and read the most of it, the idea seems really interesting to me. If you are still looking for people to work with I would like to contribute to your project.
#### My Bio
I am a Computer Engineering student graduating in a few months and as such I have little job experience apart from a few months of internships. Most of my software development knowledge is self-taught, but I have knowledge of the engineering side of things from school as well (like b-trees and TCP/IP that you mention in the post). 
#### What Can I Do
I am confortable with front end development if you are looking for teammates in that area since JavaScript is something I have experience with the most.
However I would gladly help with C# development if that is what you are looking for. My C# experience mostly comes from coding games in Unity, but I have a good grasp of OOP and I've had my training with Java which is very similar so I can quickly pick things up quickly in C# if the project needs a developer on that side.

**Comment by dynamoRando** [comment]
@MirageOwl I have Q+A with Mozilla in a few minutes, but feel free to find me on slack (Randy Le) in the mozilla builders channel. I would be happy to discuss more there.

**Comment by dynamoRando** [comment]
Hey, I'm just not going to do the spring event. Good luck to you.
